<x-marketing-layout>
    <x-slot name="title">
        Terms & Conditions - LEENA IT SOLUTIONS | {{ config('app.name', 'TurfBooking') }}
    </x-slot>

    <section class="py-12 sm:py-20 relative overflow-hidden">
        <div class="max-w-4xl mx-auto px-4 sm:px-6">
            
            <!-- Policy Navigation Tabs -->
            <x-policy-tabs active="terms" />

            <!-- Main Document Card -->
            <article class="bg-white border border-slate-200/80 rounded-3xl p-6 sm:p-12 shadow-sm relative overflow-hidden">
                
                <!-- Document Header -->
                <header class="border-b border-slate-100 pb-8 mb-8">
                    <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-50 border border-emerald-100 text-emerald-700 text-[11px] font-extrabold uppercase tracking-wider mb-4">
                        📜 Official Legal Agreement
                    </div>
                    <h1 class="text-2xl sm:text-4xl font-black text-slate-900 tracking-tight">Terms & Conditions</h1>
                    <p class="text-xs sm:text-sm text-slate-500 mt-2">
                        Platform: <a href="https://turf.infoleena.com" class="text-emerald-600 hover:underline font-medium">https://turf.infoleena.com</a> &bull; Operated by <strong>LEENA IT SOLUTIONS</strong>
                    </p>
                </header>

                <div class="space-y-8 text-xs sm:text-sm leading-relaxed text-slate-600">
                    
                    <!-- Section 1 -->
                    <div class="p-4 sm:p-5 rounded-2xl bg-slate-50 border border-slate-100 text-slate-700">
                        <p class="font-semibold text-slate-900 mb-1">1. Electronic Record Notice</p>
                        <p>
                            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                        </p>
                    </div>

                    <!-- Section 2 -->
                    <div class="space-y-2">
                        <h2 class="text-sm sm:text-base font-bold text-slate-900 flex items-center gap-2">
                            <span class="w-6 h-6 rounded-full bg-emerald-100 text-emerald-700 text-xs flex items-center justify-center font-black">2</span>
                            Publication Compliance
                        </h2>
                        <p>
                            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <strong>https://turf.infoleena.com</strong> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
                        </p>
                    </div>

                    <!-- Section 3 -->
                    <div class="p-4 sm:p-5 rounded-2xl bg-emerald-50/50 border border-emerald-100 text-slate-700">
                        <h2 class="text-sm sm:text-base font-bold text-emerald-900 flex items-center gap-2 mb-2">
                            <span class="w-6 h-6 rounded-full bg-emerald-600 text-white text-xs flex items-center justify-center font-black">3</span>
                            Platform Ownership & Registered Office
                        </h2>
                        <p>
                            The Platform is owned by <strong>LEENA IT SOLUTIONS</strong>, a company incorporated under the Companies Act, 1956 with its registered office at <strong>Plot No 65, Shree Satyam CHS B101, Sai Section, Ambernath East 421501 MS India</strong> (hereinafter referred to as ‘Platform Owner’, 'we', 'us', 'our').
                        </p>
                    </div>

                    <!-- Section 4 -->
                    <div class="space-y-2">
                        <h2 class="text-sm sm:text-base font-bold text-slate-900 flex items-center gap-2">
                            <span class="w-6 h-6 rounded-full bg-emerald-100 text-emerald-700 text-xs flex items-center justify-center font-black">4</span>
                            Binding Contract & Acceptance of Terms
                        </h2>
                        <p>
                            Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services').
                        </p>
                        <p>
                            Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
                        </p>
                    </div>

                    <!-- Section 5 -->
                    <div class="space-y-2">
                        <h2 class="text-sm sm:text-base font-bold text-slate-900 flex items-center gap-2">
                            <span class="w-6 h-6 rounded-full bg-emerald-100 text-emerald-700 text-xs flex items-center justify-center font-black">5</span>
                            Definition of User
                        </h2>
                        <p>
                            For the purpose of these Terms of Use, wherever the context so requires ‘you’, 'your' or ‘user’ shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
                        </p>
                    </div>

                    <!-- Section 6 -->
                    <div class="p-4 sm:p-5 rounded-2xl bg-amber-50 border border-amber-200 text-amber-950 font-medium">
                        <p class="font-black text-amber-900 mb-1 tracking-wide uppercase text-xs">6. Critical Notice Before Proceeding</p>
                        <p>
                            ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
                        </p>
                    </div>

                    <!-- Section 7 (Clauses 1 to 8) -->
                    <div class="space-y-4">
                        <h2 class="text-sm sm:text-base font-bold text-slate-900 flex items-center gap-2">
                            <span class="w-6 h-6 rounded-full bg-emerald-100 text-emerald-700 text-xs flex items-center justify-center font-black">7</span>
                            Terms of Use & Rules of Platform Usage
                        </h2>
                        <p>The use of Platform and/or availing of our Services is subject to the following Terms of Use:</p>
                        
                        <div class="space-y-3 ps-2 sm:ps-4">
                            <div class="flex items-start gap-3">
                                <span class="text-emerald-600 font-bold shrink-0 text-xs sm:text-sm">7.1</span>
                                <p>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</p>
                            </div>
                            <div class="flex items-start gap-3">
                                <span class="text-emerald-600 font-bold shrink-0 text-xs sm:text-sm">7.2</span>
                                <p>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</p>
                            </div>
                            <div class="flex items-start gap-3">
                                <span class="text-emerald-600 font-bold shrink-0 text-xs sm:text-sm">7.3</span>
                                <p>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</p>
                            </div>
                            <div class="flex items-start gap-3">
                                <span class="text-emerald-600 font-bold shrink-0 text-xs sm:text-sm">7.4</span>
                                <p>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.</p>
                            </div>
                            <div class="flex items-start gap-3">
                                <span class="text-emerald-600 font-bold shrink-0 text-xs sm:text-sm">7.5</span>
                                <p>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</p>
                            </div>
                            <div class="flex items-start gap-3">
                                <span class="text-emerald-600 font-bold shrink-0 text-xs sm:text-sm">7.6</span>
                                <p>You agree to pay us the charges associated with availing the Services.</p>
                            </div>
                            <div class="flex items-start gap-3">
                                <span class="text-emerald-600 font-bold shrink-0 text-xs sm:text-sm">7.7</span>
                                <p>You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</p>
                            </div>
                            <div class="flex items-start gap-3">
                                <span class="text-emerald-600 font-bold shrink-0 text-xs sm:text-sm">7.8</span>
                                <p>You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience to provide further information.</p>
                            </div>
                        </div>
                    </div>

                    <!-- Section 8 to 14 -->
                    <div class="space-y-4 pt-4 border-t border-slate-100">
                        <!-- Section 8 -->
                        <div class="space-y-1">
                            <h2 class="text-sm sm:text-base font-bold text-slate-900 flex items-center gap-2">
                                <span class="w-6 h-6 rounded-full bg-emerald-100 text-emerald-700 text-xs flex items-center justify-center font-black">8</span>
                                Enforceability & Transaction Contract
                            </h2>
                            <p>
                                You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
                            </p>
                        </div>

                        <!-- Section 9 -->
                        <div class="space-y-1">
                            <h2 class="text-sm sm:text-base font-bold text-slate-900 flex items-center gap-2">
                                <span class="w-6 h-6 rounded-full bg-emerald-100 text-emerald-700 text-xs flex items-center justify-center font-black">9</span>
                                Indemnification
                            </h2>
                            <p>
                                You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, Privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
                            </p>
                        </div>

                        <!-- Section 10 -->
                        <div class="space-y-1">
                            <h2 class="text-sm sm:text-base font-bold text-slate-900 flex items-center gap-2">
                                <span class="w-6 h-6 rounded-full bg-emerald-100 text-emerald-700 text-xs flex items-center justify-center font-black">10</span>
                                Force Majeure
                            </h2>
                            <p>
                                Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
                            </p>
                        </div>

                        <!-- Section 11 -->
                        <div class="space-y-1">
                            <h2 class="text-sm sm:text-base font-bold text-slate-900 flex items-center gap-2">
                                <span class="w-6 h-6 rounded-full bg-emerald-100 text-emerald-700 text-xs flex items-center justify-center font-black">11</span>
                                Governing Law
                            </h2>
                            <p>
                                These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
                            </p>
                        </div>

                        <!-- Section 12 -->
                        <div class="space-y-1">
                            <h2 class="text-sm sm:text-base font-bold text-slate-900 flex items-center gap-2">
                                <span class="w-6 h-6 rounded-full bg-emerald-100 text-emerald-700 text-xs flex items-center justify-center font-black">12</span>
                                Jurisdiction
                            </h2>
                            <p>
                                All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Ambernath / Thane / Mumbai, Maharashtra, India.
                            </p>
                        </div>

                        <!-- Section 13 -->
                        <div class="p-4 sm:p-5 rounded-2xl bg-slate-50 border border-slate-100 space-y-2">
                            <h2 class="text-sm sm:text-base font-bold text-slate-900 flex items-center gap-2">
                                <span class="w-6 h-6 rounded-full bg-emerald-100 text-emerald-700 text-xs flex items-center justify-center font-black">13</span>
                                Contact & Grievance Communications
                            </h2>
                            <p>
                                All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website:
                            </p>
                            <div class="text-xs space-y-1 pt-1 text-slate-700">
                                <p><strong>Company:</strong> LEENA IT SOLUTIONS</p>
                                <p><strong>Registered Address:</strong> Plot No 65, Shree Satyam CHS B101, Sai Section, Ambernath East 421501 MS India</p>
                                <p><strong>Email:</strong> <a href="mailto:leenaadam28@gmail.com" class="text-emerald-600 hover:underline">leenaadam28@gmail.com</a> / <a href="mailto:sandeep198558@gmail.com" class="text-emerald-600 hover:underline">sandeep198558@gmail.com</a></p>
                                <p><strong>Telephone:</strong> +91 9769409405 / +91 9664588677</p>
                                <p><strong>Hours:</strong> Monday &ndash; Friday (9:00 &ndash; 18:00 IST)</p>
                            </div>
                        </div>
                    </div>

                </div>
            </article>

        </div>
    </section>
</x-marketing-layout>
